### ISSUE TITLE
[Studio] Fix error or improve message when entity obfuscated w encryption not configured

### ISSUE THREAD

**Issue by francoisno** [theopenconversationkit/tock#1070]
Currently if no `tock_encrypt_pass` is configured, it is possible to set an entity type _Obfuscated_ in Tock Studio, yet going to _Inbox_ raises a technical error (toaster without details).
Looking at logs, it's a `no tock_encrypt_pass` exception.
Either fix it by having a default key, or hide the _Obfuscated_ option when not set, or improve the error message in both logs and UI.

**Comment by francoisno** [comment]
```
java.lang.IllegalStateException: no tock_encrypt_pass set
	at ai.tock.shared.security.EncryptorsKt$textEncryptor$2.invoke(Encryptors.kt:39)
	at ai.tock.shared.security.EncryptorsKt$textEncryptor$2.invoke(Encryptors.kt)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at ai.tock.shared.security.EncryptorsKt.getTextEncryptor(Encryptors.kt)
	at ai.tock.shared.security.EncryptorsKt.encrypt(Encryptors.kt:67)
	at ai.tock.nlp.admin.model.SentenceReport.<init>(SentenceReport.kt:90)
	at ai.tock.nlp.admin.model.SentencesReport.<init>(SentencesReport.kt:32)
	at ai.tock.nlp.admin.AdminService.searchSentences(AdminService.kt:75)
```
