### ISSUE TITLE
Unable to delete an entity value

### ISSUE THREAD

**Issue by edbotdemo** [theopenconversationkit/tock#1257]
![image](https://user-images.githubusercontent.com/71820900/115533184-c80cac80-a296-11eb-9aeb-2f77f4567454.png)

Unable to delete an entity value. It's ok if I import modified dictionnary but not able to remove only one value 

Regards
Camille

**Comment by vsct-jburet** [comment]
@edbotdemo please provide the server stack trace - it works on the demo platform on my side

**Comment by msansen-esncf** [comment]
Hello @vsct-jburet ,

here is the bot admin stack trace:
2021-04-27 11:51:27,346 INFO  [vert.x-worker-thread-6] a.t.n.f.s.AdminTockUserListener: register TockUser(user=admin@ed.com, namespace=ed, roles=[nlpUser, botUser, admin, technicalAdmin], registered=false)
2021-04-27 11:53:24,599 ERROR [vert.x-eventloop-thread-0] a.t.b.a.BotAdminVerticle: The positional operator did not find the match needed from the query.
com.mongodb.MongoWriteException: The positional operator did not find the match needed from the query.
        at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1017)
        at com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:993)
        at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:578)
        at com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:573)
        at ai.tock.nlp.front.storage.mongo.EntityTypeDefinitionMongoDAO.deletePredefinedValueLabelByName(EntityTypeDefinitionMongoDAO.kt:127)
        at ai.tock.nlp.front.service.ApplicationConfigurationService.deletePredefinedValueLabelByName(ApplicationConfigurationService.kt)
        at ai.tock.nlp.front.client.FrontClient.deletePredefinedValueLabelByName(FrontClient.kt)
        at ai.tock.nlp.admin.AdminVerticle$configureServices$76.invoke(AdminVerticle.kt:955)
        at ai.tock.nlp.admin.AdminVerticle$configureServices$76.invoke(AdminVerticle.kt:96)
        at ai.tock.shared.vertx.WebVerticle$blockingDelete$1.invoke(WebVerticle.kt:490)
        at ai.tock.shared.vertx.WebVerticle$blockingDelete$1.invoke(WebVerticle.kt:71)
        at ai.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:616)
        at ai.tock.shared.vertx.WebVerticle$executeBlocking$1.handle(WebVerticle.kt:71)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by vsct-jburet** [comment]
looks like a DocumentDb specific issue. Im' going to fix it
