### ISSUE TITLE
Trouble with index MongoDB on DialogFlowDAO

### ISSUE THREAD

**Issue by djowalker** [theopenconversationkit/tock#1406]
@vsct-jburet 
It tries to resolves #1395 however it creates another problem. (maybe see commit 823fd8ae0114a7237bf65212e4b4de01925f08c7)

Furthermore we use DocumentDB wich allow to use only limited indexes, and there are also limited features on it.

So it is important to use less indexes or to use `if (isDocumentDB())`
```
com.mongodb.MongoCommandException: Command failed with error 67 (CannotCreateIndex): 'namespace name generated from index name "tock_bot.flow_transition_stats_date.$applicationId_1_date_1_intent_1_storyDefinitionId_1_storyCategory_1_storyType_1_locale_1_configurationName_1_connectorType_1_actionType_1_hourOfDay_1" is too long (127 byte max)' on server mongo2:27018. The full response is {"operationTime": {"$timestamp": {"t": 1666344186, "i": 3}}, "ok": 0.0, "errmsg": "namespace name generated from index name \"tock_bot.flow_transition_stats_date.$applicationId_1_date_1_intent_1_storyDefinitionId_1_storyCategory_1_storyType_1_locale_1_configurationName_1_connectorType_1_actionType_1_hourOfDay_1\" is too long (127 byte max)", "code": 67, "codeName": "CannotCreateIndex", "$clusterTime": {"clusterTime": {"$timestamp": {"t": 1666344186, "i": 3}}, "signature": {"hash": {"$binary": {"base64": "AAAAAAAAAAAAAAAAAAAAAAAAAAA=", "subType": "00"}}, "keyId": 0}}}
	at com.mongodb.internal.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:198)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:413)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:337)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:240)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:116)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:345)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:250)
	at com.mongodb.internal.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:197)
	at com.mongodb.internal.operation.CreateIndexesOperation$1.call(CreateIndexesOperation.java:192)
	at com.mongodb.internal.operation.OperationHelper.withConnectionSource(OperationHelper.java:547)
	at com.mongodb.internal.operation.OperationHelper.withConnection(OperationHelper.java:538)
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:192)
	at com.mongodb.internal.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:212)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:863)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:846)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:841)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:826)
	at org.litote.kmongo.MongoCollectionsKt.ensureIndex(MongoCollections.kt:664)
	at org.litote.kmongo.MongoCollectionsKt.ensureIndex(MongoCollections.kt:680)
	at ai.tock.shared.MongosKt.ensureIndex(Mongos.kt:253)
	at ai.tock.shared.MongosKt.ensureIndex$default(Mongos.kt:248)
	at ai.tock.bot.mongo.DialogFlowMongoDAO.<clinit>(DialogFlowMongoDAO.kt:165)
	at ai.tock.bot.mongo.UserTimelineMongoDAO$save$7.invoke(UserTimelineMongoDAO.kt:292)
	at ai.tock.bot.mongo.UserTimelineMongoDAO$save$7.invoke(UserTimelineMongoDAO.kt:240)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1.invoke(Executor.kt:69)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1.access$invoke(Executor.kt:17)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1$executeBlocking$2$1.invoke(Executor.kt:34)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1$executeBlocking$2$1.invoke(Executor.kt:33)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1.invokeWithLoggingContext(Executor.kt:106)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1.access$invokeWithLoggingContext(Executor.kt:17)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1$executeBlocking$2.invoke(Executor.kt:33)
	at com.arkea.inno.bot.max.ExecutorKt$maxVertxExecutor$1$executeBlocking$2.invoke(Executor.kt:32)
	at ai.tock.shared.vertx.VertXsKt.blocking$lambda$1(VertXs.kt:86)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by djowalker** [comment]
I was using integrated mode btw.
